"""Windows-side helper for the RunPod LoRA-training round trip (see
runpod_train.sh, which runs ON the pod, and README's cloud-training section).

Two subcommands:

  pack --character xinyi [--base pony]
      Renders training/config/{lora_xinyi.toml, dataset_xinyi.toml,
      xinyi_samples.txt} from the CHARACTERS profile, then zips the dataset
      (PNG + TXT only, *.npz deliberately excluded - the local fp16 caches are
      NaN-poisoned and invalid for Pony's CLIP) plus the configs plus
      runpod_train.sh into training/runpod_bundle/xinyi.zip, and prints the
      `runpodctl send` line to upload it.

  install --file <lora.safetensors> --character xinyi [--base pony]
      Copies the trained LoRA into models/lora/ and NTFS-hardlinks it into
      ComfyUI/models/loras/ (same convention as the other model files, see
      README), then prints the dict to paste into CHARACTERS[xinyi]["lora"].

This file never trains anything and never imports torch - training happens on
the pod. It only marshals data and config in/out.
"""

import argparse
import glob
import math
import os
import shutil
import subprocess
import zipfile

import generate_character as gc

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
CONFIG_DIR = os.path.join(HERE, "config")
BUNDLE_DIR = os.path.join(HERE, "runpod_bundle")
MODELS_LORA_DIR = os.path.join(ROOT, "models", "lora")
COMFY_LORA_DIR = os.path.join(ROOT, "ComfyUI", "models", "loras")

BASE_FILES = {
    "pony": "ponyDiffusionV6XL_v6StartWithThisOne.safetensors",
    "sdxl": "sd_xl_base_1.0.safetensors",
}

# Target ~200 samples/epoch regardless of dataset size, 10 epochs, batch 2 =>
# ~1000 optimizer steps (num_repeats = ceil(200 / N)).
SAMPLES_PER_EPOCH = 200
EPOCHS = 10
BATCH_SIZE = 2


def _lora_toml(trigger, dim, alpha):
    """kohya network config. Differences vs training/config/mylora.toml are
    the NaN fix (bf16 + no_half_vae, fp8_base removed), shuffle_caption on
    (needs cache_text_encoder_outputs off), batch 2, keep-all-epochs. Paths
    are passed on the CLI by runpod_train.sh, so none are hard-coded here."""
    return f"""# Auto-generated by runpod_bundle.py for character '{trigger}'.
# Trained on RunPod (bf16). Do not run on the local RTX 2070 (no bf16).
[general]
output_name = "{trigger}"
save_model_as = "safetensors"
save_every_n_epochs = 1
save_last_n_epochs = {EPOCHS}
log_with = "tensorboard"
seed = 23

[network]
network_module = "networks.lora"
network_dim = {dim}
network_alpha = {alpha}
network_train_unet_only = true

[training]
optimizer_type = "AdamW8bit"
learning_rate = 0.0001
lr_scheduler = "cosine"
lr_warmup_steps = 50
max_train_epochs = {EPOCHS}
mixed_precision = "bf16"
save_precision = "bf16"
no_half_vae = true
batch_size = {BATCH_SIZE}
gradient_checkpointing = true
max_data_loader_n_workers = 4
persistent_data_loader_workers = true
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
shuffle_caption = true
min_snr_gamma = 5
sdpa = true

[dataset]
resolution = 1024
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1280
bucket_reso_steps = 64

[sampling]
sample_every_n_epochs = 1
sample_sampler = "euler_a"
"""


def _dataset_toml(trigger, num_repeats):
    return f"""# Auto-generated by runpod_bundle.py for character '{trigger}'.
# image_dir is absolute on the pod's Network Volume; keep_tokens=1 pins the
# trigger word as the first, un-shuffled caption token so identity binds to it.
[general]
enable_bucket = true

[[datasets]]
resolution = 1024
batch_size = {BATCH_SIZE}

  [[datasets.subsets]]
  image_dir = "/workspace/datasets/{trigger}"
  caption_extension = ".txt"
  num_repeats = {num_repeats}
  keep_tokens = 1
"""


def _samples_txt(trigger, base):
    profile = gc.get_character(trigger)
    identity = gc.character_base_prompt(trigger, profile)
    quality = "score_9, score_8_up, score_7_up, " if base == "pony" else ""
    neg = f"{gc.SAFE_SAFETY_NEGATIVE}, {gc.REALISTIC_NEGATIVE}"
    # Two probes: a clean studio frontal (identity check) and a different
    # outfit/scene (does it still follow the prompt, or has it burned in?).
    line1 = (f"{quality}{identity}, front view portrait, soft studio lighting, "
             f"{gc.REALISTIC_STYLE} --n {neg} --w 1024 --h 1024 --l 7 --s 20 --d 23")
    line2 = (f"{quality}{identity}, sitting in a cafe, warm afternoon light, casual outfit, "
             f"{gc.REALISTIC_STYLE} --n {neg} --w 1024 --h 1024 --l 7 --s 20 --d 42")
    return line1 + "\n" + line2 + "\n"


def cmd_pack(args):
    trigger = args.character
    base = args.base
    gc.get_character(trigger)  # validate

    data_dir = os.path.join(ROOT, "datasets", trigger)
    pngs = sorted(glob.glob(os.path.join(data_dir, "*.png")))
    if not pngs:
        raise SystemExit(f"no *.png in {data_dir} - generate a dataset first "
                         f"(e.g. python generate_character.py variations --character {trigger} --anchor <anchor.png> --count 60)")
    n = len(pngs)
    num_repeats = max(1, math.ceil(SAMPLES_PER_EPOCH / n))
    # Smaller network for tiny datasets to resist overfitting.
    dim, alpha = (16, 8) if n < 20 else (32, 16)

    os.makedirs(CONFIG_DIR, exist_ok=True)
    os.makedirs(BUNDLE_DIR, exist_ok=True)

    lora_path = os.path.join(CONFIG_DIR, f"lora_{trigger}.toml")
    ds_path = os.path.join(CONFIG_DIR, f"dataset_{trigger}.toml")
    samples_path = os.path.join(CONFIG_DIR, f"{trigger}_samples.txt")
    with open(lora_path, "w", encoding="utf-8") as f:
        f.write(_lora_toml(trigger, dim, alpha))
    with open(ds_path, "w", encoding="utf-8") as f:
        f.write(_dataset_toml(trigger, num_repeats))
    with open(samples_path, "w", encoding="utf-8") as f:
        f.write(_samples_txt(trigger, base))

    print(f"dataset: {n} images -> num_repeats={num_repeats}, network_dim/alpha={dim}/{alpha}, "
          f"~{n * num_repeats} samples/epoch x {EPOCHS} epochs / batch {BATCH_SIZE} "
          f"= ~{n * num_repeats * EPOCHS // BATCH_SIZE} steps")

    zip_path = os.path.join(BUNDLE_DIR, f"{trigger}.zip")
    caption_missing = 0
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for png in pngs:
            z.write(png, f"datasets/{trigger}/{os.path.basename(png)}")
            txt = os.path.splitext(png)[0] + ".txt"
            if os.path.isfile(txt):
                z.write(txt, f"datasets/{trigger}/{os.path.basename(txt)}")
            else:
                caption_missing += 1
        z.write(lora_path, f"config/lora_{trigger}.toml")
        z.write(ds_path, f"config/dataset_{trigger}.toml")
        z.write(samples_path, f"config/{trigger}_samples.txt")
        z.write(os.path.join(HERE, "runpod_train.sh"), "runpod_train.sh")

    print(f"wrote {zip_path}")
    if caption_missing:
        print(f"WARNING: {caption_missing} images had no matching .txt caption")
    print()
    print("Next steps:")
    print(f"  1. On the pod, make sure /workspace/models/{BASE_FILES[base]} exists (download once).")
    print(f"  2. Windows: runpodctl send \"{zip_path}\"   -> copy the one-time code")
    print(f"  3. Pod: cd /workspace && runpodctl receive <code> && unzip -o {trigger}.zip")
    print(f"  4. Pod: bash runpod_train.sh {trigger} {base}")


def cmd_install(args):
    trigger = args.character
    base = args.base
    src = args.file
    if not os.path.isfile(src):
        raise SystemExit(f"LoRA file not found: {src}")
    gc.get_character(trigger)

    os.makedirs(MODELS_LORA_DIR, exist_ok=True)
    os.makedirs(COMFY_LORA_DIR, exist_ok=True)
    fname = f"{trigger}_{base}_v1.safetensors"
    dst = os.path.join(MODELS_LORA_DIR, fname)
    shutil.copy2(src, dst)
    print(f"copied -> {dst}")

    link = os.path.join(COMFY_LORA_DIR, fname)
    if os.path.exists(link):
        os.remove(link)
    # NTFS hardlink (same volume) - matches README's model-linking convention.
    try:
        subprocess.run(["cmd", "/c", "mklink", "/H", link, dst], check=True,
                       capture_output=True, text=True)
        print(f"hardlinked -> {link}")
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        shutil.copy2(dst, link)
        print(f"hardlink failed ({exc}); copied instead -> {link}")

    print()
    print(f"Paste into generate_character.py CHARACTERS['{trigger}']:")
    print(f'    "lora": {{"file": "{fname}", "trigger": "{trigger}", "base_family": "{base}",')
    print('             "strength_model": 0.8, "strength_clip": 0.8, "faceid_weight": 0.7},')


def main():
    p = argparse.ArgumentParser(description="RunPod LoRA training bundle helper (Windows side)")
    sub = p.add_subparsers(dest="cmd", required=True)

    pp = sub.add_parser("pack", help="render configs + zip the dataset for upload to RunPod")
    pp.add_argument("--character", required=True, choices=sorted(gc.CHARACTERS))
    pp.add_argument("--base", default="pony", choices=sorted(BASE_FILES),
                    help="base checkpoint family the LoRA is trained on; pony (default) suits the Pony inference checkpoints, sdxl for Juggernaut")
    pp.set_defaults(func=cmd_pack)

    pi = sub.add_parser("install", help="install a trained LoRA locally and register it")
    pi.add_argument("--file", required=True, help="path to the trained .safetensors received from the pod")
    pi.add_argument("--character", required=True, choices=sorted(gc.CHARACTERS))
    pi.add_argument("--base", default="pony", choices=sorted(BASE_FILES))
    pi.set_defaults(func=cmd_install)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
