"""The tool interface: six functions, plain dicts in and out. Whatever drives the system - an assistant with
a shell, a script, a notebook form - goes through these and nothing else. scripts/aiwf.py is the same six
functions as a command line.

    list_workflows()  create_job()  get_job_status()  list_jobs()  cancel_job()  get_result()

A caller never needs a node id, a model file name, a GPU type or a path inside the workspace: it names a
workflow, sends the values list_workflows() describes, and gets a job id back.

These functions only ever ADD files (a job in jobs/pending, a request in jobs/cancel). Moving a job through
its states is the worker's job alone - see the single-writer rule in jobs.py.
"""

from . import WorkflowError, compute, jobs, params, safety
from .registry import Registry
from .storage import open_storage

PLATFORM_CONFIG = "configs/platform.json"
IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".webp")
ATTESTATION_TEXT = (
    "The image is either one generated by this project's own pipeline (a fictional adult character) or contains "
    "no person. It is not a photo of a real person."
)


class Context:
    """Storage, registry and compute provider for one workspace."""

    def __init__(self, storage):
        self.storage = storage
        self.config = storage.read_json(PLATFORM_CONFIG, {}) or {}
        self.registry = Registry.load(storage)
        self.store = jobs.JobStore(storage)
        self.provider = compute.make_provider(self.config)


def open_context(root=None, storage=None):
    return Context(storage if storage is not None else open_storage(root))


def _worker_note(ctx):
    worker = ctx.provider.worker_state(ctx.storage)
    note = {"worker": worker}
    if not worker["alive"]:
        note["hint"] = ctx.provider.start_hint()
    elif not worker["serving"]:
        note["hint"] = ctx.provider.serve_hint()
    return note


# --- inputs (files a job needs) ------------------------------------------------------------------


def _normalise_input_ref(name, spec, ref):
    if ref is None:
        ref = {"source": spec.get("default_source")}
    elif isinstance(ref, str):  # shorthand: a source name, a path under inputs/, or a job id
        if ref in spec["sources"]:
            ref = {"source": ref}
        elif ref.replace("\\", "/").startswith("inputs/"):
            ref = {"source": "file", "path": ref}
        else:
            ref = {"source": "job", "job_id": ref}
    if not isinstance(ref, dict) or ref.get("source") not in spec["sources"]:
        raise WorkflowError(
            "INVALID_INPUT",
            "%s needs a source, one of %s" % (name, spec["sources"]),
            hint='e.g. {"source": "generate"}',
        )
    return dict(ref)


def _resolve_inputs(ctx, workflow, job_id, values, raw_inputs, created):
    """Turn each declared input into a reference the worker can verify. Returns (refs, depends_on)."""
    refs, depends = {}, []
    for name, spec in workflow.inputs.items():
        ref = _normalise_input_ref(name, spec, raw_inputs.get(name))
        source = ref["source"]
        if source == "generate":
            gen = spec["generate"]
            prompt = values.get(gen["prompt_param"]) or values.get(gen["fallback_prompt_param"])
            child_values = {"prompt": prompt}
            for passed in gen.get("pass", []):
                if values.get(passed) is not None:
                    child_values[passed] = values[passed]
            if workflow.profile == safety.PROFILE_SCREENED_PROMPT:
                safety.screen_prompt(prompt or "")
            child = _build_job(ctx, gen["workflow"], child_values, {}, None, "chain", created, parent=job_id)
            ref = {"source": "generate", "job_id": child["job_id"]}
            depends.append(child["job_id"])
        elif source == "job":
            dep = ctx.store.get(jobs.check_job_id(ref.get("job_id")))
            dep_type = ctx.registry.workflows.get(dep["workflow"])
            if dep_type is None or dep_type.type != spec["kind"]:
                raise WorkflowError(
                    "INVALID_INPUT", "%s: job %s is not an %s job" % (name, dep["job_id"], spec["kind"])
                )
            if dep["status"] in (jobs.FAILED, jobs.CANCELLED):
                raise WorkflowError("INVALID_INPUT", "%s: job %s ended as %s" % (name, dep["job_id"], dep["status"]))
            ref = {"source": "job", "job_id": dep["job_id"]}
            if dep["status"] != jobs.COMPLETED:
                depends.append(dep["job_id"])
        else:  # file
            path = str(ref.get("path") or "").replace("\\", "/")
            if not path.startswith("inputs/") or ".." in path.split("/") or not path.lower().endswith(IMAGE_SUFFIXES):
                raise WorkflowError(
                    "INVALID_INPUT", "%s: path must be an image under inputs/ (%s)" % (name, ", ".join(IMAGE_SUFFIXES))
                )
            if source in spec.get("attestation_sources", []) and ref.get("attested") is not True:
                raise WorkflowError(
                    "ATTESTATION_REQUIRED",
                    "%s: a file from inputs/ cannot be checked by the system, so its use must be confirmed." % name,
                    hint='Confirm, and pass "attested": true, only if this is true: %s' % ATTESTATION_TEXT,
                )
            ref = {
                "source": "file",
                "path": path,
                "attested": bool(ref.get("attested")),
                "attestation": ATTESTATION_TEXT,
            }
        refs[name] = ref
    return refs, depends


def _build_job(ctx, workflow_name, values, raw_inputs, task_type, source, created, parent=None):
    workflow = ctx.registry.get(workflow_name)
    task_types = workflow.get("task_types", [])
    if task_type is None:
        task_type = task_types[0] if task_types else workflow.type
    elif task_types and task_type not in task_types:
        raise WorkflowError(
            "INVALID_INPUT", "workflow %s does not do %r; it does %s" % (workflow_name, task_type, task_types)
        )
    unknown = sorted(set(raw_inputs) - set(workflow.inputs))
    if unknown:
        raise WorkflowError("INVALID_INPUT", "unknown input(s) %s for workflow %s" % (unknown, workflow_name))
    normal = params.validate(workflow, values)
    if workflow.profile == safety.PROFILE_SCREENED_PROMPT:
        for text in params.texts(workflow, normal):
            safety.screen_prompt(text)
    else:
        params.composed(workflow, normal)
    job_id = jobs.new_job_id()
    refs, depends = _resolve_inputs(ctx, workflow, job_id, normal, raw_inputs, created)
    job_input, job_params = params.split(workflow, normal)
    job_input.update(refs)
    job = jobs.new_job(
        job_id,
        workflow=workflow_name,
        task_type=task_type,
        job_input=job_input,
        parameters=job_params,
        source=source,
        depends_on=depends,
        parent=parent,
    )
    created.append(job)
    return job


# --- the six tools -------------------------------------------------------------------------------


def list_workflows(root=None, *, context=None):
    ctx = context or open_context(root)
    out = {"workflows": [ctx.registry.workflows[name].describe() for name in ctx.registry.names()]}
    if ctx.registry.problems:
        out["problems"] = {name: exc.as_dict() for name, exc in ctx.registry.problems.items()}
    return out


def create_job(workflow, input=None, parameters=None, task_type=None, root=None, *, source="tool", context=None):
    """Validate and queue a job. `input` and `parameters` may be given in either dict; the registry decides
    where each value is stored. A workflow whose input is generated by another workflow (a video's first frame)
    queues that job too and waits for it; `jobs` in the result lists everything that was created."""
    ctx = context or open_context(root)
    values, raw_inputs = {}, {}
    wf = ctx.registry.get(workflow)
    for group in (input or {}, parameters or {}):
        if not isinstance(group, dict):
            raise WorkflowError("INVALID_INPUT", "input and parameters must be objects")
        for key, value in group.items():
            (raw_inputs if key in wf.inputs else values)[key] = value
    created = []
    job = _build_job(ctx, workflow, values, raw_inputs, task_type, source, created)
    # Nothing is written until every job of the chain validated; dependencies are written first.
    for item in sorted(created, key=lambda j: j["job_id"] == job["job_id"]):
        ctx.store.create(item)
    out = {
        "job_id": job["job_id"],
        "status": job["status"],
        "workflow": workflow,
        "jobs": [j["job_id"] for j in created],
    }
    out.update(_worker_note(ctx))
    return out


def _brief(job):
    return {
        key: job.get(key)
        for key in ("job_id", "workflow", "task_type", "status", "created_at", "started_at", "completed_at", "error")
    }


def get_job_status(job_id, root=None, *, context=None):
    ctx = context or open_context(root)
    job = ctx.store.get(job_id)
    out = _brief(job)
    out["depends_on"] = job.get("depends_on", [])
    if job["status"] not in jobs.TERMINAL:
        if ctx.store.cancel_requested(job_id):
            out["cancel_requested"] = True
        out.update(_worker_note(ctx))
        waiting = out["worker"].get("waiting", {}).get(job_id)
        if waiting:
            out["waiting"] = waiting
    return out


def list_jobs(status=None, limit=50, root=None, *, context=None):
    ctx = context or open_context(root)
    if status is not None and status not in jobs.STATUSES:
        raise WorkflowError("INVALID_INPUT", "status must be one of %s" % list(jobs.STATUSES))
    found = ctx.store.list(status)
    counts = {}
    for job in found:
        counts[job["status"]] = counts.get(job["status"], 0) + 1
    return {"jobs": [_brief(j) for j in found[-int(limit) :]], "counts": counts, "total": len(found)}


def cancel_job(job_id, root=None, *, context=None):
    """Ask for a job to be cancelled. The request is honoured by the worker (a queued job is dropped, a running
    one is interrupted); with no worker running it stays a request until one starts."""
    ctx = context or open_context(root)
    job = ctx.store.get(job_id)
    if job["status"] in jobs.TERMINAL:
        return {"job_id": job_id, "status": job["status"], "cancel_requested": False}
    ctx.store.request_cancel(job_id)
    out = {"job_id": job_id, "status": job["status"], "cancel_requested": True}
    out.update(_worker_note(ctx))
    return out


def get_result(job_id, root=None, *, context=None):
    ctx = context or open_context(root)
    job = ctx.store.get(job_id)
    out = _brief(job)
    if job["status"] != jobs.COMPLETED:
        out["output"] = None
        return out
    output = dict(job["output"])
    local = ctx.storage.local_path(output["path"])
    if local is not None:
        output["local_path"] = str(local)
        output["available_locally"] = local.is_file()
    out["output"] = output
    for key in ("generation_seconds", "gpu", "vram_peak_mib"):
        out[key] = job.get(key)
    return out


TOOLS = {
    "list_workflows": list_workflows,
    "create_job": create_job,
    "get_job_status": get_job_status,
    "list_jobs": list_jobs,
    "cancel_job": cancel_job,
    "get_result": get_result,
}
